### ISSUE TITLE
REST Docs Adjustments

### ISSUE THREAD

**Issue by davidgrieser** [gajjuCoderBoi/java-pundits-invoicify#66]
Please drop a level from the ToC and remove redundant reference in subtitles.

<img width="746" alt="Screen Shot 2021-05-21 at 12 19 02 PM" src="https://user-images.githubusercontent.com/292375/119175255-35933080-ba2f-11eb-85fb-d1a2aafd6582.png">

**Comment by whediger** [comment]
For the subtitles I would suggest a RESTful description of the end point
Under the Company category you could do:
rather than: AddCompany
you could have: POST /company
