### ISSUE TITLE
RESTful Routes

### ISSUE THREAD

**Issue by davidgrieser** [gajjuCoderBoi/java-pundits-invoicify#67]
Please follow a more RESTful routing convention for your endpoints. Feel free to create additional GitHub Issues and link back to this one as you feel is required.

METHOD | Results | Payload
--------- | -------- | -------
`GET /invoice` | All Invoices | n/a
`POST /invoice` | Create Invoice | `{ "companyId": <companyId> }`
`GET /invoice/{invoiceId}` | View single Invoice | n/a
`GET /invoice/{invoiceId}/item` | Return all Items on an Invoice | n/a
`GET /invoice/{invoiceId}/item/{itemId}` | Return Item on Invoice | n/a
`POST /invoice/{invoiceId}/item` | Add Line Item to Invoice | Current JSON is fine

![Screen Shot 2021-05-14 at 5 27 08 PM](https://user-images.githubusercontent.com/292375/119175589-9d497b80-ba2f-11eb-87c5-55242d3f723d.png)

**Comment by gajjuCoderBoi** [comment]
I would recommend send companyId as request parameter then rest body.

**Comment by gajjuCoderBoi** [comment]
2nd last is not good I think. ItemId is unique id so it can fetched by only ItemId no need to send invoiceId.

**Comment by davidgrieser** [comment]
The goal of including the `companyId` in the Request Body, has to do with having a consistent URL API that is being interacted with.

If you want to have the `companyId` in the URL. I'd be fine with `POST /company/{companyId}/invoice` with invoice details.

Example of this can be seen here: https://docs.github.com/en/rest/reference/repos#create-an-organization-repository

As for the items list. Both endpoint of `GET /item/{itemId}` and `GET /invoice/{invoiceId}/item/{itemId}` can exist. However, if an `itemId` isn't associated with the nested invoice it should 404.
