### ISSUE TITLE
Create Invoice with all details

### ISSUE THREAD

**Issue by davidgrieser** [gajjuCoderBoi/java-pundits-invoicify#68]
Ability to POST a full Invoice Payload to save it all in 1 request.

`POST /invoice`

```.json
{
    "companyId": 12,
    "paymentStatus": "UNPAID",
    "items": [
        {
            "description": "Test Item",
            "quantity": 5,
            "feeType": "RATE",
            "rate": 10.0
        },
        {
            "description": "Test Item",
            "quantity": 5,
            "feeType": "RATE",
            "rate": 10.0
        }
    ]
}
```

**Comment by gajjuCoderBoi** [comment]
We have add post invoice item. So it's not necessary.

**Comment by davidgrieser** [comment]
While this endpoint does exist, I want to use a service similar to Apigee which charges based on the number of requests and making 3 requests when 1 would suffice is a new requirement.
